### ISSUE TITLE
primary key values copied with ARRAY

### ISSUE THREAD

**Issue by Benni5K** [gam17/QAD#14] opened 2017-03-10 09:42 UTC
Sorry for bothering you with the next issue! I found a little problem when using ARRAYRECT or one of the other array tools. I'm working on PostGIS-Data with primary key auto generated by DBMS. When I create new objects with QGIS or QAD tools, primary key value is nextval('my_schema.my_id_seq'::regclass) and gets generated when savig edits. Copying objects with QGIS or QAD tools does the same. But when I copy objects with QADs ARRAY tools, primary key of the origin object is copied to new objects. Because of non unique pk's, DBMS throws an error when safing edits. As a workaround I catch this by updating pk's before insert. But in long term I don't want to have too much functionality on server side, so it would be cool if QAD recognizes pk's and leaves it empty when using ARRAY.
Thanks a lot!
Benni

**Comment by gam17** [comment] 2017-03-11 10:36
Hi Benni,
it's a bug ! I'am working on it...

**Comment by gam17** [comment] 2017-03-15 06:48
Hi Benni,
    here is a zip file containing the new version of QAD plugin with 2 
bugs fixed.
I am referring to issue 14 and 13. Can you test it ?, i need to be sure 
it is all right now.
let me know...


> Sorry for bothering you with the next issue! I found a little problem
> when using ARRAYRECT or one of the other array tools. I'm working on
> PostGIS-Data with primary key auto generated by DBMS. When I create
> new objects with QGIS or QAD tools, primary key value is
> nextval('my_schema.my_id_seq'::regclass) and gets generated when savig
> edits. Copying objects with QGIS or QAD tools does the same. But when
> I copy objects with QADs ARRAY tools, primary key of the origin object
> is copied to new objects. Because of non unique pk's, DBMS throws an
> error when safing edits. As a workaround I catch this by updating pk's
> before insert. But in long term I don't want to have too much
> functionality on server side, so it would be cool if QAD recognizes
> pk's and leaves it empty when using ARRAY.
> Thanks a lot!
> Benni

**Comment by Benni5K** [comment] 2017-03-15 08:21
Hi, maybe the attached files didnt get sent via email reply? Please attach on github, I'm lookling forward to test!

**Comment by gam17** [comment] 2017-03-15 18:36
Sorry ! here the file  [qad.zip](https://github.com/gam17/QAD/files/845627/qad.zip)

**Comment by Benni5K** [comment] 2017-03-20 10:08
Hi gam17, thank you very much for the zip file to test! I was out of office the last four days, so sorry for my late reply.

#14 (primary key values copied with ARRAY): Basically works great now. Just one little thing I didn't realize before: The origin object is considered as new too after using ARRAY and its primary key is replaced by default value 'nextval('my_schema.my_id_seq'::regclass)'. It was the same with my BEFORE INSERT workaround on server side, the pk-value got updated too. I think the origin object should keep it's pk value as it it's only changed but not created new using the ARRAY tools (at least from the users point of view). Thats also what users are used too when they change objects with QGIS vector tools.
#13: Please see my answer in the issue.
Thanks for your great work!

**Comment by gam17** [comment] 2017-03-21 16:14
QAD array command is similar to autocad array command. Both use DELOBJ system variable. Run SETVAR command or type DELOBJ in the QAD text window to set it.
QAD supports only the 3 following values for DELOBJ system variable:
0 ->All defining geometry is retained. 
1 -> Removes all defining geometry.
-1 ->Displays prompts to delete geometry.
hope it helps

p.s.
In this last QAD version, you can select the command options using right click.

**Comment by Benni5K** [comment] 2017-03-22 12:15
Thank you for the explanation! Absolutely makes sense that QAD does the way AutoCAD does. Command options via right click ist great!
Regards
Benni

**Comment by Benni5K** [comment] 2017-03-22 13:48
I just had the oportunity to compare with AutoCAD Map 3D. There, after using ARRAY tool, all new objects show the same pk than the origin objects and all objects including origin object are marked as changed (little pen in attribute table). After 'Check in' the new objects get a new pk but the origin object keeps its pk.
With QAD, pk of origin object and new objects is set to 'nextval('my_schema.my_id_seq'::regclass)' straight after using ARRAY so all pk including origin object getting changed.

**Comment by Benni5K** [comment] 2017-03-22 14:09
Additional Information: In AutoCAD Map 3D with DELOBJ on 0 a new object with new pk is created on top of origin object and origin object is retained with unchanged pk. With DELOBJ on 1 (or 3), behaviour is as described in my last comment.

**Comment by gam17** [comment] 2017-03-27 06:35
Related to
"With QAD, pk of origin object and new objects is set to 'nextval('my_schema.my_id_seq'::regclass)' straight after using ARRAY so all pk including origin object getting changed."

Sorry, I can't reproduce this strange behaviour. In my installation pk of the origin object doesn't change. Can you report, step by step, what I have to do to reproduce the problem ?
Thank you

**Comment by Benni5K** [comment] 2017-03-27 08:25
Hi, thanks for reopening. Hope you can reproduce with the following steps:

1. Create new table on PostGIS-DB:
_CREATE TABLE test.qadtest
(
  id bigserial NOT NULL,
  the_geom geometry(Polygon,31468),
  CONSTRAINT pk_qadtest PRIMARY KEY (id)
)_

2. Create new QGIS project with OTF CRS transformation enabled, EPSG:31468

3. Load above PostGIS source, enable editing.

3. Create new rectangle geometry using QAD, save edits, id value of this first geometry is set to '1'.

4. Enable editing again, use ARRAYRECT:
_Command: ARRAYRECT
found 1
Select an option to edit array or [Base point/Angle/COUnt/Spacing/Columns/Rows/rotate Items/eXit] <eXit>: C
Specify number of columns <5>: 2
Specify distance between columns or [Total] <10.0>: 15
Select an option to edit array or [Base point/Angle/COUnt/Spacing/Columns/Rows/rotate Items/eXit] <eXit>: R
Specify number of rows <5>: 2
Specify distance between rows or [Total] <10.0>: 15
Select an option to edit array or [Base point/Angle/COUnt/Spacing/Columns/Rows/rotate Items/eXit] <eXit>: A
Specify the angle of rotation for the row axis <0.0>: 15
Select an option to edit array or [Base point/Angle/COUnt/Spacing/Columns/Rows/rotate Items/eXit] <eXit>:_ 

5. Outcome: 

with DELOBJ = 1: 4 geometries in table, all id values are nextval('test.qadtest_id_seq'::regclass)'
with DELOBJ = 0: 5 geometries in table, origin object unchanged, 4 new with id values nextval('test.qadtest_id_seq'::regclass)'


To compare with AutoCAD Map 3D, I do the following there:

Create new project, load same PostGIS datasource, use ARRAY:
_Command: ARRAY
1 found
Enter array type [Rectangular/PAth/POlar] <Rectangular>: R
Type = Rectangular  Associative = No
Select grip to edit array or [ASsociative/Base point/COUnt/Spacing/COLumns/Rows/Levels/eXit]<eXit>: COL
Enter the number of columns or [Expression] <4>: 2
Specify the distance between columns or [Total/Expression] <18.3712>: 15
Select grip to edit array or [ASsociative/Base point/COUnt/Spacing/COLumns/Rows/Levels/eXit]<eXit>: R
Enter the number of rows or [Expression] <3>: 2
Specify the distance between rows or [Total/Expression] <18.3712>: 15
Specify the incrementing elevation between rows or [Expresson] <0.0000>:
Select grip to edit array or [ASsociative/Base point/COUnt/Spacing/COLumns/Rows/Levels/eXit]<eXit>:_

Outcome in AutoCAD Map 3D:

with DELOBJ = 1: 4 geometries in table, origin object unchanged, 3 new objects getting new id value after checking in
with DELOBJ = 0: 5 geometries in table, origin object unchanged, 4 new objects getting new id value after checking in

**Comment by gam17** [comment] 2017-03-28 08:45
I think QAD is right. What I don't understand is why AutoCAD Map 3D creates only 3 new objects with DELOBJ = 1. May I close this issue ?

**Comment by Benni5K** [comment] 2017-03-28 09:52
Sorry, my description was a bit confusing. With DELOBJ = 1 in AutoCAD Map 3D the origin object is also marked with a little pen , so you could also consider it as a new object. The difference is that its pk value is unchanged after checking in while in QAD it's getting a new pk value. Can you reproduce that behaviour with QAD at all?
Anyway, maybe it's just a minor thing for most users if pk of origin stays the same or not. Only thing is, if there where some foreign key relations to that object they would get lost.
Of course for me it's OK to close the issue. As I know the behaviour of QAD's ARRAY concerning pk values I can work with it well and rechange pk if it should be important.
Thanks for all your effort to bring QAD ahead!
Regards
Benni

**Comment by gam17** [comment] 2017-03-28 14:00
Using QAD with DELOBJ=1 the origin object must be deleted (you write that autocad map consider it as a new object). With DELOBJ=0 the origin object is retained and its pk value doesn't change (in my test). Are you sure that an existing object change its pk value ?

**Comment by Benni5K** [comment] 2017-03-29 07:47
Sorry for confusion again. I think AutoCAD and QAD do nearly the same: 
For example, with DELOBJ = 1, when I create a 4 by 4 array without rotation, both delete the origin object and create one new object with very same geometry as the origin object (lets say object A) and three new objects in given distance (objects B,C,D).
The only difference is in pk of object A: AutoCAD adopts the pk of this object from origin object, QAD does not and a new pk is given to that object when I save changes on db.
Here, I think AutoCAD's behaviour makes more sense at least in the 'GIS users way of thinking'. The users impression is that the origin object isn't changed at all (or is changed but not created new using rotation in QAD), so users might not understand why it gets a new pk. Of course, thats despite the fact, that origin object is actually deleted and 'recreated' in background.
Hope this explains a bit better, but as I said for me it's also fine to leave it as it is, I don't want you to struggle forever with that issue.
Regards
Benni

**Comment by gam17** [comment] 2017-03-30 19:36
ok, thanks for the explaination

**Closed by gam17** 2017-03-30 19:36 UTC
