### ISSUE TITLE
Click on Blank causes Fault

### ISSUE THREAD

**Issue by ngodber** [gam17/QAD#21] opened 2017-10-13 02:09 UTC
Hi, 

I am getting the following error:

![image](https://user-images.githubusercontent.com/11834846/31527240-2f03c1f4-b00f-11e7-9628-eb0c91d1fced.png)

I triggered it simply by creating a new layer and clicking on a blank space.

It also triggers when simply selecting the 'create line segment' tool.

Thanks for your help!

Neil

**Comment by ngodber** [comment] 2017-10-13 02:16
Ok, a bit more information. It clearly seems to be related to the snap settings. I am trying to snap to a vector file (dxf) that has been imported. I've specified the CRS though so I'm curious that this is coming up.

**Comment by gam17** [comment] 2017-10-16 15:14
hi Neil,
   can you send me the dxf and the CRS you use ?
I want to reproduce the error...

gam17

**Comment by ngodber** [comment] 2017-10-18 01:31
Hey,

I've uploaded the project and file that I'm using. If you just open it and click on a blank space that should trigger the error. 

Neil
[Files.zip](https://github.com/gam17/QAD/files/1393157/Files.zip)

**Comment by gam17** [comment] 2017-10-18 09:39
I can't reproduce the error. 
What QAD version are you using ?
Read the title of QAD command text window...
Please try the last version of QAD.
gam17

**Comment by gam17** [comment] 2017-12-29 17:44
After waiting for an answer I have decided to close this issue.

**Closed by gam17** 2017-12-29 17:44 UTC
